services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: goalify
      POSTGRES_PASSWORD: goalify
    volumes:
      - ${VOLUME_LOCATION}:/var/lib/postgresql/data
    ports:
      - "5432:5432"
