services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: goalify
      POSTGRES_PASSWORD: goalify
    volumes:
        - /postgres:/var/lib/goalify/data
    ports:
        - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: goalify@goalify.com
      PGADMIN_DEFAULT_PASSWORD: goalify
    ports:
        - "5050:80"