services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: goalify
      POSTGRES_PASSWORD: goalify
    ports:
      - "5432:5432"
